### ISSUE TITLE
[Cache] NUMA aware Web-cache processing

### ISSUE THREAD

**Issue by krizhanovsky** [natsys/tempesta#122]
Current design of NUMA aware Web-caching is awkward and unfinished.

We're doing our best to finish all necessary request processing jobs on local node before scheduling it to remote NUMA node. Thus, we add all necessary HTTP proxy headers with complex skb segmentation issues while a request should not be sent to upstream server at all. The better design is required.

Also we must cache original responses, probably with only common for all clients transformations. But definitely do not cache sticky cookies and other session specific data.

**Comment by krizhanovsky** [comment]
From #119:

2.    Currently a response from a backend server is cached after it's sent to the client. That means it's cached along with all additions from Tempesta, such as those in tfw_http_adjust_resp(), and possibly a sticky cookie. That's not right. Ideally, a response should be cached in the form it had come from the server, before any additions from Tempesta are applied. However, currently caching is done asynchronously in attempt to make it NUMA-aware and NUMA-optimized. Doing it in a synchronous way doesn't seem like a desirable option. With that in mind, there's no obvious way to cache a response before any changes. Recall, that all changes are applied "in place", and that greatly complicates this issue.

3. If a response is found in cache, most probably it should be modified in tfw_http_req_cache_cb(). The modifications include whatever is in tfw_http_adjust_resp(), as well as a possible addition of sticky cookie. Also, see the topic (2) on proper caching described above.

4.    When response is found in cache, certain internal fields should be set up to facilitate response modifications. For instance, those are resp->crlf, and possibly resp->body. Functions that do the modifications expect these pointers and use them. (See the above two topics (2) and (3)).

5.    Do we need to keep data argument to tfw_http_req_cache_cb(), and to all functions on the way to it, like tfw_cache_req_process()? Could it be that we'll need it again later?

8.    An attempt to use response caching ended up in a crash in the code that writes response data to TDB. From the look of it, it appears that lots of response caching, retrieval, building code is quite old and outdated. That's an issue to work on.

**Comment by krizhanovsky** [comment]
Linked with #173: data from cache and sent through socket can be splitted by Linux networking code.

**Comment by krizhanovsky** [comment]
Actually, ```tso_fragment()``` and ```tcp_fragment()``` work with skb page fragments and don't mangle original data pages (this is basically how ```tcp_sendpage()``` works) as well as skb linear (head) data. However, new socket buffers can be allocated on segmentation and/or retransmission.

Meantime, ```ip_fragment()``` can do heavy copying of large, typically segmented, skbs and this is unwished. So GSO should be supported by NIC and ```skb_is_gso()``` should be true for skbs from the cache (see ```ip_finish_output()```). Large linear data can also cause data copying.

Thus, it's safe to pass data to TCP/IP send code, but large linear data and GSO-disabled networking should be avoided to minimize copying.

**Comment by keshonok** [comment]
Issues raised and analysed here and in #173, all originate from the way SKBs are treated in Linux TCP/IP stack. So instead of holding onto SKBs with data, Tempesta needs to hold onto the data itself.
Tempesta processes an HTTP message carried in SKB data, and creates a list of pointers into that HTTP message. Later the pointers are used for proper caching of the HTTP message. As we keep hold on data itself, these pointer will stay valid even after SKBs are transmitted.

- Most of SKB data is kept in pages, and pages are reference counted. Tempesta needs to take an extra reference on these pages to guarantee that it keeps a hold on them.
- Some SKB data may be kept in the linear part. If an HTTP message is very small a complete message may end up in the linear part. Most probably there's no other way here other than copy the data to a page allocated for that purpose.
- At the same time, drivers for some high-performance network adapters, such as Intel's `ixgbe`, specifically put all data to pages, and it's an extremely rare case when the whole HTTP message plus network headers would fit into 256 bytes the driver allocates for the linear part of an SKB. Still, a driver can be modified so that it never puts data in the linear part, however small that data is.
- It may also help that these drivers often allocate a page for an SKB header that holds the linear part and the shared info of an SKB. `skb->head_frag` is set in that case.
- There's also a fragment list in SKB that may carry data.
- As we don't hold onto SKB anymore, managing of SKBs gets simpler. Tempesta can release all SKB when it passes them back to TCP/IP stack, and the stack will take care of freeing them later. There's no need then for taking a share on an SKB, or a special patch in `kfree_skb()`.
- Caching can be done asynchronously, as we're not bound by the limitation of holding onto SKBs anymore.

I have to note that we still need the code in Tempesta that deals with the linear part (copies it to a page). That would allow for continuous development of Tempesta in other environments, such as VMs.
